[package]
name = "ext4-fs"
version = "0.1.5"
edition = "2024"
license = "MIT"
repository = "https://github.com/puffyCid/ext4-fs"
description = "A very basic library to read the ext4 filesystem"
keywords = ["forensics"]

[dependencies]
nom = "8.0.0"
serde = { version = "1.0.228", features = ["derive"] }
tracing = "0.1.44"
base64 = "0.22.1"
uuid = { version = "1.23.1", features = ["v4"] }
md-5 = "0.11.0"
sha1 = "0.11.0"
sha2 = "0.11.0"
base16ct = { version = "1.0.0", default-features = false }
digest-io = { version = "0.1.0", default-features = false }
