on:
  push:
    tags:
      - v[0-9]+.*

name: Publish

jobs:
  crates_publish:
    name: Publish (crates.io)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5
        with:
          persist-credentials: false
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@6d653acede28d24f02e3cd41383119e8b1b35921 #v2025.09.23
        with:
          toolchain: stable
          components: rustfmt, clippy
          targets: ${{ matrix.info.target }}

      - name: Logon to Crates
        run: cargo login ${{ secrets.CRATES_IO_API_TOKEN }}
      - name: "Publish"
        run: cargo publish